/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.*;
/**
 *
 * @author PC
 */
public class NewJFrame extends javax.swing.JFrame {

    
     String operators = null;
    double number1 =0, number2 = 0;
   
   
  
    
    public NewJFrame() {
        initComponents();
        
        BUANS.setBackground(Color.blue);
        BU1.setBackground(Color.black);
        BU1.setForeground(Color.white);
        BU2.setBackground(Color.black);
        BU2.setForeground(Color.white);
        BU3.setBackground(Color.black);
        BU3.setForeground(Color.white);
        BU4.setBackground(Color.black);
        BU4.setForeground(Color.white);
        BU5.setBackground(Color.black);
        BU5.setForeground(Color.white);
        BU6.setBackground(Color.black);
        BU6.setForeground(Color.white);
        BU7.setBackground(Color.black);
        BU7.setForeground(Color.white);
        BU8.setBackground(Color.black);
        BU8.setForeground(Color.white);
        BU9.setBackground(Color.black);
        BU9.setForeground(Color.white);
        BU0.setBackground(Color.black);
        BU0.setForeground(Color.white);
        
        BUADD.setBackground(Color.orange);
        BUADD.setForeground(Color.black);
        
        BUSUB.setBackground(Color.gray);
        BUSUB.setForeground(Color.white);
        
        BUMULTİ.setBackground(Color.gray);
        BUMULTİ.setForeground(Color.white);
        
        BUDİVİ.setBackground(Color.gray);
        BUDİVİ.setForeground(Color.white);
        
        
        
        BUDEL.setBackground(Color.gray);
        BUDEL.setForeground(Color.white);
        
        BUC.setBackground(Color.gray);
        BUC.setForeground(Color.white);
        
        BUDOT.setBackground(Color.gray);
        BUDOT.setForeground(Color.white);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf = new javax.swing.JTextField();
        BUADD = new javax.swing.JButton();
        BUANS = new javax.swing.JButton();
        BU9 = new javax.swing.JButton();
        BU4 = new javax.swing.JButton();
        BU6 = new javax.swing.JButton();
        BU5 = new javax.swing.JButton();
        BU7 = new javax.swing.JButton();
        BU8 = new javax.swing.JButton();
        BUDOT = new javax.swing.JButton();
        BUDEL = new javax.swing.JButton();
        BUC = new javax.swing.JButton();
        BU0 = new javax.swing.JButton();
        BU3 = new javax.swing.JButton();
        BU2 = new javax.swing.JButton();
        BU1 = new javax.swing.JButton();
        BUSUB = new javax.swing.JButton();
        BUMULTİ = new javax.swing.JButton();
        BUDİVİ = new javax.swing.JButton();

        jButton5.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("                        CALCULATOR");

        tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tf.setText("Enter the values or operations");
        tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfActionPerformed(evt);
            }
        });

        BUADD.setText("+");
        BUADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUADDActionPerformed(evt);
            }
        });

        BUANS.setText("ANS");
        BUANS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUANSActionPerformed(evt);
            }
        });

        BU9.setText("9");
        BU9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BU9ActionPerformed(evt);
            }
        });

        BU4.setText("4");
        BU4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BU4ActionPerformed(evt);
            }
        });

        BU6.setText("6");
        BU6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BU6ActionPerformed(evt);
            }
        });

        BU5.setText("5");
        BU5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BU5ActionPerformed(evt);
            }
        });

        BU7.setText("7");
        BU7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BU7ActionPerformed(evt);
            }
        });

        BU8.setText("8");
        BU8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BU8ActionPerformed(evt);
            }
        });

        BUDOT.setText(".");
        BUDOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUDOTActionPerformed(evt);
            }
        });

        BUDEL.setText("DEL");
        BUDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUDELActionPerformed(evt);
            }
        });

        BUC.setText("C");
        BUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUCActionPerformed(evt);
            }
        });

        BU0.setText("0");
        BU0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BU0ActionPerformed(evt);
            }
        });

        BU3.setText("3");
        BU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BU3ActionPerformed(evt);
            }
        });

        BU2.setText("2");
        BU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BU2ActionPerformed(evt);
            }
        });

        BU1.setText("1");
        BU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BU1ActionPerformed(evt);
            }
        });

        BUSUB.setText("-");
        BUSUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSUBActionPerformed(evt);
            }
        });

        BUMULTİ.setText("*");
        BUMULTİ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUMULTİActionPerformed(evt);
            }
        });

        BUDİVİ.setText("/");
        BUDİVİ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUDİVİActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BUC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BUDEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BUSUB, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(BUMULTİ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BUDİVİ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BU7, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(BU4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(BU8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BU1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BU2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(BU5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(BU0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BU6, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(BU9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BU3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BUDOT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BUADD, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BUANS, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BUSUB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BUMULTİ, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BUDİVİ, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BU9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BU7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BU8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(BU4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(BU5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BU6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(BUDEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(BUADD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BU2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BU3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(BU1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BUDOT, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BU0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BUC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BUANS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfActionPerformed

    private void BUANSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUANSActionPerformed
        // TODO add your handling code here:
        
        number2= Double.parseDouble(tf.getText());
        
        double result =0;
        
        if(operators=="+")
            result=number1+number2;
        else if(operators=="-")
            result=number1-number2;
        else if(operators=="*")
            result=number1*number2;
        else if(operators=="/")
            result=number1/number2;
        
        tf.setText(result+"");
        operators=null;
    }//GEN-LAST:event_BUANSActionPerformed

    private void BUDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUDELActionPerformed
        // TODO add your handling code here:
        
        tf.setText("");
        
        
    }//GEN-LAST:event_BUDELActionPerformed

    private void BU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BU1ActionPerformed
        // TODO add your handling code here:
        tf.setText(tf.getText()+"1");
    }//GEN-LAST:event_BU1ActionPerformed

    private void BU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BU3ActionPerformed
        // TODO add your handling code here:
         tf.setText(tf.getText()+"3");
    }//GEN-LAST:event_BU3ActionPerformed

    private void BU0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BU0ActionPerformed
        // TODO add your handling code here:
         tf.setText(tf.getText()+"0");
         
    }//GEN-LAST:event_BU0ActionPerformed

    private void BU5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BU5ActionPerformed
        // TODO add your handling code here:
         tf.setText(tf.getText()+"5");
    }//GEN-LAST:event_BU5ActionPerformed

    private void BUMULTİActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUMULTİActionPerformed
        // TODO add your handling code here:
        number1= Double.parseDouble(tf.getText());
        tf.setText("");
        operators="*";
    }//GEN-LAST:event_BUMULTİActionPerformed

    private void BUDİVİActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUDİVİActionPerformed
        // TODO add your handling code here:
        number1=Double.parseDouble(tf.getText());
        tf.setText("");
        operators="/";
    }//GEN-LAST:event_BUDİVİActionPerformed

    private void BU4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BU4ActionPerformed
        // TODO add your handling code here:
         tf.setText(tf.getText()+"4");
    }//GEN-LAST:event_BU4ActionPerformed

    private void BU7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BU7ActionPerformed
        // TODO add your handling code here:
         tf.setText(tf.getText()+"7");
    }//GEN-LAST:event_BU7ActionPerformed

    private void BU8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BU8ActionPerformed
        // TODO add your handling code here:
         tf.setText(tf.getText()+"8");
    }//GEN-LAST:event_BU8ActionPerformed

    private void BU9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BU9ActionPerformed
        // TODO add your handling code here:
         tf.setText(tf.getText()+"9");
    }//GEN-LAST:event_BU9ActionPerformed

    private void BU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BU2ActionPerformed
        // TODO add your handling code here:
         tf.setText(tf.getText()+"2");
    }//GEN-LAST:event_BU2ActionPerformed

    private void BU6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BU6ActionPerformed
        // TODO add your handling code here:
         tf.setText(tf.getText()+"6");
    }//GEN-LAST:event_BU6ActionPerformed

    private void BUDOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUDOTActionPerformed
        // TODO add your handling code here:
         tf.setText(tf.getText()+".");
    }//GEN-LAST:event_BUDOTActionPerformed

    private void BUADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUADDActionPerformed
        // TODO add your handling code here:
        number1 = Double.parseDouble(tf.getText()) ;
        tf.setText("");
        operators = "+";
    }//GEN-LAST:event_BUADDActionPerformed

    private void BUSUBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSUBActionPerformed
        // TODO add your handling code here:
        
         number1=Double.parseDouble(tf.getText());
         tf.setText("");
         operators="-";
    }//GEN-LAST:event_BUSUBActionPerformed

    private void BUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUCActionPerformed
        // TODO add your handling code here:
        
        String s =tf.getText();
        
        tf.setText(s.substring(0,s.length()-1));
    }//GEN-LAST:event_BUCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BU0;
    private javax.swing.JButton BU1;
    private javax.swing.JButton BU2;
    private javax.swing.JButton BU3;
    private javax.swing.JButton BU4;
    private javax.swing.JButton BU5;
    private javax.swing.JButton BU6;
    private javax.swing.JButton BU7;
    private javax.swing.JButton BU8;
    private javax.swing.JButton BU9;
    private javax.swing.JButton BUADD;
    private javax.swing.JButton BUANS;
    private javax.swing.JButton BUC;
    private javax.swing.JButton BUDEL;
    private javax.swing.JButton BUDOT;
    private javax.swing.JButton BUDİVİ;
    private javax.swing.JButton BUMULTİ;
    private javax.swing.JButton BUSUB;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tf;
    // End of variables declaration//GEN-END:variables
}
